import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";
import { observer } from "mobx-react-lite";
import { useStore } from "../components/StoreProvider";
import axios from "axios";
import { ICategory } from "../models";

const Home: NextPage = () => {
  const { t, lang } = useTranslation();

  const store = useStore();

  useEffect(() => {
    store.start();

    // stop the clock when the component unmounts
    return () => {
      store.stop();
    };
  }, [store]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App 「{t("home:title")}」</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>{t("home:title")}</div>
        <div>{store.timeString}</div>

        <div>
          {store.categoryList.map((category: ICategory) => {
            return <div key={category.id}>{category.name}</div>;
          })}
        </div>

        <button onClick={() => store.getCategoryList()}>egt</button>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default observer(Home);

export async function getServerSideProps() {
  const api = "http://192.168.1.13:6001/v1/grandet_public/nft_get_categories";
  const { data } = await axios.post(api);

  return {
    props: {
      initialState: {
        lastUpdate: Date.now(),
        categoryList: data.data,
      },
    },
  };
}
